#!/bin/bash
########################
# Command to apply puppet to this system
########################

sudo puppet apply /etc/puppet/manifests --modulepath=/etc/puppet/modules $*
#  EOF  ################
